[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
# Main
name = "agp-manim"
version = "0.2.0"
# Dependecies
requires-python = ">3.8,<3.14"
dependencies = ["requests", "importlib-metadata"]

# About project
authors = [
    { name = "VEF_renovator", email = "vladimir_e11@outlook.com" },
    { name = "emhayki" },
]
maintainers = [{ name = "VEF_renovator", email = "vladimir_e11@outlook.com" }]
description = "A ManimCE animation explaining Fisk's proof of the solution to the Art Gallery Problem (AGP)"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
keywords = [
    "art-gallery-problem",
    "visualization",
    "triangulation",
    "tircolor",
    "manim",
]
urls = { Repository = "https://github.com/VEFrenovator/Art-Gallery-Problem--manim" }

[project.optional-dependencies]
manim-slides-present = ["manim-slides[full]", "PyQt6", "PySide6"]
dev = [
    "numpy",
    "shapely",
    "mapbox-earcut",
    "pillow",
    "manim",
    "agp-manim[manim-slides-present]",
]
# Full is alias for dev
full = ["apg-manim[dev]"]

[tool.setuptools]
packages = [
    "agp_manim",
    "agp_manim.animations",
    "agp_manim.static",
    "agp_manim.utils",
    "agp_manim.animations.backdrop",
]
package-dir = { "agp_manim.animations.backdrop" = "agp_manim/animations/backdrop_animations_submodule" }
